package br.com.avaliadorfuzzy.model;
// default package
// Generated 07/09/2011 11:20:36 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Regra generated by hbm2java
 */
@Entity
@Table(name = "regra", catalog = "avaliadorfuzzydb")
public class Regra implements java.io.Serializable {

	private int idRegra;
	private Termo termoByIdTermoConforto;
	private Termo termoByIdTermoTempo;
	private Termo termoByIdTermoAvaliacao;
	private int indAntecedente;

	public Regra() {
	}

	public Regra(int idRegra, Termo termoByIdTermoConforto,
			Termo termoByIdTermoTempo, Termo termoByIdTermoAvaliacao,
			int indAntecedente) {
		this.idRegra = idRegra;
		this.termoByIdTermoConforto = termoByIdTermoConforto;
		this.termoByIdTermoTempo = termoByIdTermoTempo;
		this.termoByIdTermoAvaliacao = termoByIdTermoAvaliacao;
		this.indAntecedente = indAntecedente;
	}

	@Id
	@Column(name = "idRegra", unique = true, nullable = false)
	public int getIdRegra() {
		return this.idRegra;
	}

	public void setIdRegra(int idRegra) {
		this.idRegra = idRegra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTermoConforto", nullable = false)
	public Termo getTermoByIdTermoConforto() {
		return this.termoByIdTermoConforto;
	}

	public void setTermoByIdTermoConforto(Termo termoByIdTermoConforto) {
		this.termoByIdTermoConforto = termoByIdTermoConforto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTermoTempo", nullable = false)
	public Termo getTermoByIdTermoTempo() {
		return this.termoByIdTermoTempo;
	}

	public void setTermoByIdTermoTempo(Termo termoByIdTermoTempo) {
		this.termoByIdTermoTempo = termoByIdTermoTempo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTermoAvaliacao", nullable = false)
	public Termo getTermoByIdTermoAvaliacao() {
		return this.termoByIdTermoAvaliacao;
	}

	public void setTermoByIdTermoAvaliacao(Termo termoByIdTermoAvaliacao) {
		this.termoByIdTermoAvaliacao = termoByIdTermoAvaliacao;
	}

	@Column(name = "indAntecedente", nullable = false)
	public int getIndAntecedente() {
		return this.indAntecedente;
	}

	public void setIndAntecedente(int indAntecedente) {
		this.indAntecedente = indAntecedente;
	}

}
