package br.com.avaliadorfuzzy.model;
// default package
// Generated 07/09/2011 11:20:36 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Segmento generated by hbm2java
 */
@Entity
@Table(name = "segmento", catalog = "avaliadorfuzzydb")
public class Segmento implements java.io.Serializable {

	private int idSegmento;
	private Termo termo;
	private double intervaloEsquerdo;
	private double intervaloDireito;
	private double miEsquerdo;
	private double miDireito;

	public Segmento() {
	}

	public Segmento(int idSegmento, Termo termo, double intervaloEsquerdo,
			double intervaloDireito, double miEsquerdo, double miDireito) {
		this.idSegmento = idSegmento;
		this.termo = termo;
		this.intervaloEsquerdo = intervaloEsquerdo;
		this.intervaloDireito = intervaloDireito;
		this.miEsquerdo = miEsquerdo;
		this.miDireito = miDireito;
	}

	@Id
	@Column(name = "idSegmento", unique = true, nullable = false)
	public int getIdSegmento() {
		return this.idSegmento;
	}

	public void setIdSegmento(int idSegmento) {
		this.idSegmento = idSegmento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTermo", nullable = false)
	public Termo getTermo() {
		return this.termo;
	}

	public void setTermo(Termo termo) {
		this.termo = termo;
	}

	@Column(name = "intervaloEsquerdo", nullable = false, precision = 22, scale = 0)
	public double getIntervaloEsquerdo() {
		return this.intervaloEsquerdo;
	}

	public void setIntervaloEsquerdo(double intervaloEsquerdo) {
		this.intervaloEsquerdo = intervaloEsquerdo;
	}

	@Column(name = "intervaloDireito", nullable = false, precision = 22, scale = 0)
	public double getIntervaloDireito() {
		return this.intervaloDireito;
	}

	public void setIntervaloDireito(double intervaloDireito) {
		this.intervaloDireito = intervaloDireito;
	}

	@Column(name = "miEsquerdo", nullable = false, precision = 22, scale = 0)
	public double getMiEsquerdo() {
		return this.miEsquerdo;
	}

	public void setMiEsquerdo(double miEsquerdo) {
		this.miEsquerdo = miEsquerdo;
	}

	@Column(name = "miDireito", nullable = false, precision = 22, scale = 0)
	public double getMiDireito() {
		return this.miDireito;
	}

	public void setMiDireito(double miDireito) {
		this.miDireito = miDireito;
	}

}
