package br.com.avaliadorfuzzy.model;
// default package
// Generated 07/09/2011 11:20:36 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Termo generated by hbm2java
 */
@Entity
@Table(name = "termo", catalog = "avaliadorfuzzydb")
public class Termo implements java.io.Serializable {

	private int idTermo;
	private Variavellinguistica variavellinguistica;
	private String nome;
	private Set<Regra> regrasForIdTermoTempo = new HashSet<Regra>(0);
	private Set<Regra> regrasForIdTermoConforto = new HashSet<Regra>(0);
	private Set<Regra> regrasForIdTermoAvaliacao = new HashSet<Regra>(0);
	private Set<Segmento> segmentos = new HashSet<Segmento>(0);

	public Termo() {
	}

	public Termo(int idTermo, Variavellinguistica variavellinguistica,
			String nome) {
		this.idTermo = idTermo;
		this.variavellinguistica = variavellinguistica;
		this.nome = nome;
	}

	public Termo(int idTermo, Variavellinguistica variavellinguistica,
			String nome, Set<Regra> regrasForIdTermoTempo,
			Set<Regra> regrasForIdTermoConforto,
			Set<Regra> regrasForIdTermoAvaliacao, Set<Segmento> segmentos) {
		this.idTermo = idTermo;
		this.variavellinguistica = variavellinguistica;
		this.nome = nome;
		this.regrasForIdTermoTempo = regrasForIdTermoTempo;
		this.regrasForIdTermoConforto = regrasForIdTermoConforto;
		this.regrasForIdTermoAvaliacao = regrasForIdTermoAvaliacao;
		this.segmentos = segmentos;
	}

	@Id
	@Column(name = "idTermo", unique = true, nullable = false)
	public int getIdTermo() {
		return this.idTermo;
	}

	public void setIdTermo(int idTermo) {
		this.idTermo = idTermo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idVariavelLinguistica", nullable = false)
	public Variavellinguistica getVariavellinguistica() {
		return this.variavellinguistica;
	}

	public void setVariavellinguistica(Variavellinguistica variavellinguistica) {
		this.variavellinguistica = variavellinguistica;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "termoByIdTermoTempo")
	public Set<Regra> getRegrasForIdTermoTempo() {
		return this.regrasForIdTermoTempo;
	}

	public void setRegrasForIdTermoTempo(Set<Regra> regrasForIdTermoTempo) {
		this.regrasForIdTermoTempo = regrasForIdTermoTempo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "termoByIdTermoConforto")
	public Set<Regra> getRegrasForIdTermoConforto() {
		return this.regrasForIdTermoConforto;
	}

	public void setRegrasForIdTermoConforto(Set<Regra> regrasForIdTermoConforto) {
		this.regrasForIdTermoConforto = regrasForIdTermoConforto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "termoByIdTermoAvaliacao")
	public Set<Regra> getRegrasForIdTermoAvaliacao() {
		return this.regrasForIdTermoAvaliacao;
	}

	public void setRegrasForIdTermoAvaliacao(
			Set<Regra> regrasForIdTermoAvaliacao) {
		this.regrasForIdTermoAvaliacao = regrasForIdTermoAvaliacao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "termo")
	public Set<Segmento> getSegmentos() {
		return this.segmentos;
	}

	public void setSegmentos(Set<Segmento> segmentos) {
		this.segmentos = segmentos;
	}

}
